apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs-pv
  namespace: airflow-cluster
spec:
  storageClassName: local-path
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/rancher/k3s/storage/airflow-logs-pv"  # Update this path accordingly
  # Node affinity is usually not needed unless you have specific requirements